# Generated by Django 4.1 on 2022-11-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('promo_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('promo_type', models.CharField(max_length=50)),
                ('promo_name', models.CharField(max_length=25)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MinimumTransactionPromo',
            fields=[
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='promo.promo')),
                ('minimum_transaction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDayPromo',
            fields=[
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='promo.promo')),
                ('promo_date', models.DateField()),
            ],
        ),
    ]
